version: '3.8'

services:
  quizapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./Data:/app/Data
    restart: unless-stopped
    
  quizapp-tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    volumes:
      - ./test-results:/test-results